---
- name: Configure RustyIP VPS
  hosts: vps
  become: true
  gather_facts: true

  vars:
    app_image: "{{ lookup('env', 'APP_IMAGE') }}"
    site_domain: "{{ lookup('env', 'SITE_DOMAIN') }}"
    db_update_url: "{{ lookup('env', 'DB_UPDATE_URL') }}"
    origin_cert: "{{ lookup('env', 'ORIGIN_CERT') }}"
    origin_key: "{{ lookup('env', 'ORIGIN_KEY') }}"
    ipv4_domain: "{{ lookup('env', 'IPV4_DOMAIN') | default('', true) }}"
    ipv4_origin_cert: "{{ lookup('env', 'IPV4_ORIGIN_CERT') | default('', true) }}"
    ipv4_origin_key: "{{ lookup('env', 'IPV4_ORIGIN_KEY') | default('', true) }}"
    dockerhub_token: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    first_deploy: "{{ lookup('env', 'FIRST_DEPLOY') | default('false', true) }}"

  roles:
    - role: base
      when: first_deploy | bool
    - role: docker
      when: first_deploy | bool
    - role: app
